In [9]:
import pandas as pd
import numpy as np
from scipy import linalg
import statsmodels.api as sm

df = pd.read_csv('http://vincentarelbundock.github.io/Rdatasets/csv/datasets/longley.csv', index_col=0)

In [11]:
y = df.Employed
X = df.GNP
X = sm.add_constant(X)
X.head()

const      GNP
1947    1.0  234.289
1948    1.0  259.426
1949    1.0  258.054
1950    1.0  284.599
1951    1.0  328.975

In [13]:
#this is the same thing as b = (X'X)^-1 X'Y
theta = linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
theta

array([  5.18435898e+01,   3.47522943e-02])

In [14]:
est = sm.OLS(y, X)
est = est.fit()
est.summary()

/Users/smoot/anaconda/lib/python2.7/site-packages/scipy/stats/stats.py:1557: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               Employed   R-squared:                       0.967
Model:                            OLS   Adj. R-squared:                  0.965
Method:                 Least Squares   F-statistic:                     415.1
Date:                Thu, 23 Jun 2016   Prob (F-statistic):           8.36e-12
Time:                        11:05:36   Log-Likelihood:                -14.904
No. Observations:                  16   AIC:                             33.81
Df Residuals:                      14   BIC:                             35.35
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const         51.8436      0.681     76.087      0.000        50.382    53.305
GNP            0.0348      0.002     20.374      0.000         0.031     0.038
==============================================================================
Omnibus:                        1.925   Durbin-Watson:                   1.619
Prob(Omnibus):                  0.382   Jarque-Bera (JB):                1.215
Skew:                           0.664   Prob(JB):                        0.545
Kurtosis:                       2.759   Cond. No.                     1.66e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.66e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [15]:
est.predict(X)

array([ 59.98567007,  60.8592385 ,  60.81155835,  61.734058  ,
        63.27622581,  63.90260117,  64.54155685,  64.46256489,
        65.65654946,  66.41105653,  67.2308284 ,  67.29258322,
        68.61866127,  69.31012767,  69.8512904 ,  71.1274294 ])

In [16]:
linalg.inv(X.T.dot(X)).dot(X.T).dot(y).dot(X.T)

array([ 59.98567007,  60.8592385 ,  60.81155835,  61.734058  ,
        63.27622581,  63.90260117,  64.54155685,  64.46256489,
        65.65654946,  66.41105653,  67.2308284 ,  67.29258322,
        68.61866127,  69.31012767,  69.8512904 ,  71.1274294 ])

In [4]:
df.head()

GNP.deflator      GNP  Unemployed  Armed.Forces  Population  Year  \
1947          83.0  234.289       235.6         159.0     107.608  1947   
1948          88.5  259.426       232.5         145.6     108.632  1948   
1949          88.2  258.054       368.2         161.6     109.773  1949   
1950          89.5  284.599       335.1         165.0     110.929  1950   
1951          96.2  328.975       209.9         309.9     112.075  1951   

      Employed  
1947    60.323  
1948    61.122  
1949    60.171  
1950    61.187  
1951    63.221